[package]
name = "CHIP8_Emulator"
version = "0.1.0"
authors = ["Matthew Bland <MEBland8141@muleriders.saumag.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
